//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensorStandard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SensorStandard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- edited with XMLSpy v2006 sp2 U (http://www.altova.com) by Assi B. (Elbit) --&gt;
        ///&lt;!-- edited with XML Spy v2006 sp2 U (http://www.xmlspy.com) by Edan Ayal (Elsec) --&gt;
        ///&lt;!-- edited by Roi Shraga (hatal - project mrs) june 2017--&gt;
        ///&lt;!-- edited by Or Saffar (hatal - project mrs) Mar 2019--&gt;
        ///&lt;snsr_std:schema xmlns=&quot;urn:SNSR_STD&quot; xmlns:snsr_std=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;urn:SNSR_STD&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///	&lt;snsr_std:annotation&gt;
        ///		&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BasicTypes {
            get {
                return ResourceManager.GetString("BasicTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- edited with XMLSpy v2006 sp2 U (http://www.altova.com) by Assi B. (Elbit) --&gt;
        ///&lt;!-- edited with XML Spy v2006 sp2 U (http://www.xmlspy.com) by Edan Ayal (Elsec) --&gt;
        ///&lt;!-- edited by Roi Shraga (hatal - project mrs) june 2017--&gt;
        ///&lt;!-- edited by Or Saffar (hatal - project mrs) Mar 2019--&gt;
        ///&lt;snsr_std:schema xmlns:snsr_std=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;urn:SNSR_STD&quot; targetNamespace=&quot;urn:SNSR_STD&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///	&lt;snsr_std:include schemaLo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ControlMessage {
            get {
                return ResourceManager.GetString("ControlMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- edited with XMLSpy v2006 sp2 U (http://www.altova.com) by Assi B. (Elbit) --&gt;
        ///&lt;!-- edited with XML Spy v2006 sp2 U (http://www.xmlspy.com) by Edan Ayal (Elsec) --&gt;
        ///&lt;!-- edited by Roi Shraga (hatal - project mrs) june 2017--&gt;
        ///&lt;!-- edited by Or Saffar (hatal - project mrs) Mar 2019--&gt;
        ///&lt;snsr_std:schema xmlns=&quot;urn:SNSR_STD&quot; xmlns:snsr_std=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;urn:SNSR_STD&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///	&lt;snsr_std:include schemaLo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SensorConfiguration {
            get {
                return ResourceManager.GetString("SensorConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- edited with XMLSpy v2006 sp2 U (http://www.altova.com) by Assi B. (Elbit) --&gt;
        ///&lt;!-- edited with XML Spy v2006 sp2 U (http://www.xmlspy.com) by Edan Ayal (Elsec) --&gt;
        ///&lt;!-- edited by Roi Shraga (hatal - project mrs) june 2017--&gt;
        ///&lt;!-- edited by Or Saffar (hatal - project mrs) Mar 2019--&gt;
        ///&lt;snsr_std:schema xmlns=&quot;urn:SNSR_STD&quot; xmlns:snsr_std=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;urn:SNSR_STD&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///	&lt;snsr_std:include schemaLo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SensorIndicationReport {
            get {
                return ResourceManager.GetString("SensorIndicationReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- edited with XMLSpy v2006 sp2 U (http://www.altova.com) by Assi B. (Elbit) --&gt;
        ///&lt;!-- edited with XML Spy v2006 sp2 U (http://www.xmlspy.com) by Edan Ayal (Elsec) --&gt;
        ///&lt;!-- edited by Roi Shraga (hatal - project mrs) june 2017--&gt;
        ///&lt;!-- edited by Or Saffar (hatal - project mrs) Mar 2019--&gt;
        ///&lt;snsr_std:schema xmlns=&quot;urn:SNSR_STD&quot; xmlns:snsr_std=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;urn:SNSR_STD&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///	&lt;snsr_std:include schemaLo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SensorStatusReport {
            get {
                return ResourceManager.GetString("SensorStatusReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- edited with XML Spy v2006 sp2 U (http://www.xmlspy.com) by Edan Ayal (Elsec) --&gt;
        ///&lt;snsr_std:schema xmlns=&quot;urn:SNSR_STD&quot; xmlns:snsr_std=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;urn:SNSR_STD&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///	&lt;snsr_std:include schemaLocation=&quot;SensorConfiguration.xsd&quot;/&gt;
        ///	&lt;snsr_std:annotation&gt;
        ///		&lt;snsr_std:documentation&gt;Sensor Subscription used in the generic sensor protocol.&lt;/snsr_std:documentation&gt;
        ///	&lt;/snsr_std:annotation&gt;
        ///	&lt;!-- 
        ///	    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SubscriptionConfiguration {
            get {
                return ResourceManager.GetString("SubscriptionConfiguration", resourceCulture);
            }
        }
    }
}
